name: Client Tests

on:
  push:
    branches: [master]
    paths: ['client/**']

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
        working-directory: ./client
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run build
          start: pnpm run preview
          wait-on: http://127.0.0.1:10010
          browser: chrome
          record: true
          working-directory: client
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
