name: Server Tests

on:
  push:
    branches: [master]
    paths: ['server/**']

jobs:
  vitest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
        working-directory: ./server
      - name: Write secrets to `.dev.vars`
        run: |
          echo "CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}" > .dev.vars
          echo "API_KEY=${{ secrets.CF_WORKER_TOKEN }}" >> .dev.vars
        working-directory: ./server
      - name: Generate coverage report
        run: pnpm run coverage
        working-directory: ./server
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./server/coverage/
          files: ./clover.xml,./coverage-final.json
